apiVersion: batch/v1
kind: Job
metadata:
  name: add-model-job
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccount: feedback-ai-sa
      serviceAccountName: feedback-ai-sa
      initContainers:
      containers:
      - name: add-model
        image: quay.io/jkeam/granite-7b:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: aws-connection-minio
      restartPolicy: Never
