apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: add-model-job-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: add-model-job
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccount: feedback-ai-sa
      serviceAccountName: feedback-ai-sa
      initContainers:
      containers:
      - name: add-model
        image: "quay.io/jkeam/granite-7b@sha256:73258a5db16ea70450a19d024c822ffcdaecf55badfd3ccad2faf199d7242ca1"
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: aws-connection-minio
        volumeMounts:
            - name: temp
              mountPath: /tmp/models
      restartPolicy: Never
      volumes:
        - name: temp
          persistentVolumeClaim:
            claimName: add-model-job-pvc
