apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feedback

commonLabels:
  app: granite
  component: model

secretGenerator:
- name: aws-connection-minio
  envs:
  - .env
patches:
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: aws-connection-minio
      labels:
        opendatahub.io/dashboard: "true"
        opendatahub.io/managed: "true"
      annotations:
        opendatahub.io/connection-type: s3
        openshift.io/display-name: MinIO

resources:
- serviceaccount.yaml
- add-model-job.yaml
# - serving-runtime.yaml
# - inference-service.yaml
