apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feedback  

images:
- name: IMAGE
  newName: quay.io/jkeam/smartfeedback
  digest: sha256:6a474e570717be43597c20c0fdaf023fce7d67f35ba26f7564795bb01bd5a9a2

secretGenerator:
- name: app-secrets
  envs:
  - .env

resources:
- deployment.yaml
- service.yaml
- route.yaml
