apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feedback

images:
- name: IMAGE
  newName: quay.io/jkeam/smartfeedback
  digest: sha256:9ef8fefc50cc96f18afd04d1e0dc9cc2a71605d301d44a22854d33133fae4fc0

secretGenerator:
- name: app-secrets
  envs:
  - .env

resources:
- deployment.yaml
- service.yaml
- route.yaml
