FROM registry.access.redhat.com/ubi9/python-312:1-20.1724040035
USER root

# libs
RUN dnf install -y git-lfs
RUN pip install boto3

# transfer
USER 1001
COPY ./transfer.py .
CMD ["python", "./transfer.py"]
